import { Platform, StyleSheet } from "react-native";

export default StyleSheet.create({ 
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  header: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1e293b',
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#dc2626',
    marginTop: 2,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  workloadPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  workloadPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#fef2f2',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  logoutButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#dc2626',
  },
  content: {
    flex: 1,
    padding: 16,
  },
  statusCardsScroll: {
    marginBottom: 20,
  },
  statusCardsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  statusCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 12,
    minWidth: 90,
    borderTopWidth: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
    alignItems: 'center',
    gap: 6,
  },
  statusCardLabel: {
    fontSize: 10,
    color: '#64748b',
    fontWeight: '600',
    textAlign: 'center',
  },
  statusCardCount: {
    fontSize: 20,
    fontWeight: '700',
  },
  capacityBar: {
    backgroundColor: '#f1f5f9',
    borderRadius: 99,
    height: 4,
    overflow: 'hidden',
    width: '100%',
    marginTop: 4,
  },
  capacityFill: {
    height: '100%',
    borderRadius: 99,
  },
  searchSection: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
    fontSize: 14,
    color: '#1e293b',
  },
  refreshButton: {
    backgroundColor: '#dc2626',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  jobCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  staleCardHigh: {
    borderColor: '#dc2626',
    borderWidth: 1.5,
  },
  staleCardMedium: {
    borderColor: '#d97706',
    borderWidth: 1.5,
  },
  cardHeader: {
    backgroundColor: '#f8fafc',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    gap: 6,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    flex: 1,
  },
  jobSheetNo: {
    color: '#dc2626',
    fontWeight: '700',
    fontSize: 14,
  },
  transferBadge: {
    backgroundColor: '#fffbeb',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  transferBadgeText: {
    color: '#d97706',
    fontSize: 9,
    fontWeight: '600',
  },
  staleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  staleBadgeText: {
    fontSize: 10,
    fontWeight: '600',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '600',
  },
  cardBody: {
    padding: 16,
  },
  customerName: {
    fontWeight: '700',
    fontSize: 15,
    color: '#1e293b',
    marginBottom: 8,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  contactText: {
    fontSize: 13,
    color: '#64748b',
  },
  deviceText: {
    fontSize: 13,
    color: '#475569',
  },
  visualIssuesText: {
    fontSize: 12,
    color: '#dc2626',
  },
  remarksText: {
    fontSize: 12,
    color: '#16a34a',
  },
  transferNoteBox: {
    backgroundColor: '#fffbeb',
    padding: 8,
    borderRadius: 6,
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  transferNoteText: {
    fontSize: 12,
    color: '#d97706',
    flex: 1,
  },
  dateText: {
    fontSize: 11,
    color: '#94a3b8',
  },
  statusButtonsContainer: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 12,
    marginTop: 10,
  },
  sectionLabel: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '600',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  statusButtonsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 2,
  },
  statusButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
  },
  statusButtonActive: {
    opacity: 0.8,
  },
  statusButtonText: {
    fontSize: 11,
    fontWeight: '600',
  },
  transferButton: {
    borderColor: '#d97706',
    backgroundColor: '#fffbeb',
  },
  transferButtonText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#d97706',
  },
  deliveredMessage: {
    backgroundColor: '#f0fdf4',
    padding: 10,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  deliveredMessageText: {
    fontSize: 12,
    color: '#16a34a',
    fontWeight: '500',
  },
  repairStepsContainer: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 12,
    marginTop: 10,
  },
  repairStepsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  repairStepsHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  stepCount: {
    marginLeft: 6,
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 7,
    paddingVertical: 1,
    borderRadius: 10,
    color: '#475569',
    fontSize: 10,
  },
  progressBar: {
    backgroundColor: '#f1f5f9',
    borderRadius: 4,
    height: 4,
    marginBottom: 12,
  },
  progressFill: {
    backgroundColor: '#16a34a',
    borderRadius: 4,
    height: 4,
  },
  stepsList: {
    gap: 8,
    marginBottom: 12,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#fafafa',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 12,
  },
  stepItemDone: {
    backgroundColor: '#f0fdf4',
    borderColor: '#86efac',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: '#16a34a',
    borderColor: '#16a34a',
  },
  stepContent: {
    flex: 1,
  },
  stepText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1e293b',
  },
  stepTextDone: {
    color: '#16a34a',
    textDecorationLine: 'line-through',
  },
  stepMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
  },
  stepNote: {
    fontSize: 11,
    color: '#64748b',
  },
  stepCompletedBy: {
    fontSize: 10,
    color: '#64748b',
  },
  stepCompletedAt: {
    fontSize: 10,
    color: '#16a34a',
  },
  noStepsText: {
    fontSize: 13,
    color: '#94a3b8',
    textAlign: 'center',
    padding: 16,
  },
  addStepForm: {
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderStyle: 'dashed',
  },
  addStepTitle: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '600',
    marginBottom: 6,
  },
  stepInput: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 6,
    padding: 10,
    fontSize: 13,
    marginBottom: 8,
    color: '#1e293b',
    backgroundColor: '#ffffff',
  },
  addStepButton: {
    backgroundColor: '#dc2626',
    borderRadius: 6,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  addStepButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  loadingContainer: {
    padding: 60,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    color: '#64748b',
    fontSize: 14,
  },
  emptyContainer: {
    padding: 60,
    alignItems: 'center',
  },
  emptyText: {
    marginTop: 12,
    color: '#94a3b8',
    fontSize: 14,
  },
  jobsList: {
    gap: 16,
  },
  bottomPadding: {
    height: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  transferModalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    width: '90%',
    maxHeight: '80%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1e293b',
  },
  // Transfer Modal Styles - Fixed Alignment
  transferJobInfoContainer: {
    backgroundColor: '#f8fafc',
    marginHorizontal: 18,
    marginTop: 8,
    marginBottom: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  transferJobInfo: {
    fontSize: 13,
    color: '#64748b',
    paddingVertical: 2,
  },
  transferJobInfoBold: {
    fontWeight: '700',
    color: '#dc2626',
  },
  transferLabel: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '600',
    marginBottom: 6,
    marginTop: 12,
    paddingHorizontal: 18,
  },
  transferSelect: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    marginHorizontal: 18,
    maxHeight: 200,
    backgroundColor: '#ffffff',
  },
  transferOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  transferOptionActive: {
    backgroundColor: '#fef2f2',
  },
  transferOptionDisabled: {
    opacity: 0.5,
  },
  transferOptionText: {
    fontSize: 13,
    color: '#1e293b',
    flex: 1,
  },
  transferOptionSelected: {
    color: '#dc2626',
    fontWeight: '600',
  },
  transferOptionDisabledText: {
    color: '#94a3b8',
  },
  transferCheckmark: {
    marginLeft: 'auto',
  },
  transferDivider: {
    height: 1,
    backgroundColor: '#e2e8f0',
    marginHorizontal: 0,
  },
  transferSectionHeader: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
    padding: 10,
    paddingHorizontal: 14,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  workloadHintContainer: {
    marginHorizontal: 18,
    marginTop: 10,
  },
  workloadHintFull: {
    backgroundColor: '#fef2f2',
    padding: 8,
    borderRadius: 6,
  },
  workloadHintTextFull: {
    color: '#dc2626',
    fontSize: 12,
    fontWeight: '600',
  },
  workloadHintWarning: {
    backgroundColor: '#fffbeb',
    padding: 8,
    borderRadius: 6,
  },
  workloadHintTextWarning: {
    color: '#d97706',
    fontSize: 12,
    fontWeight: '600',
  },
  workloadHintOk: {
    backgroundColor: '#f0fdf4',
    padding: 8,
    borderRadius: 6,
  },
  workloadHintTextOk: {
    color: '#16a34a',
    fontSize: 12,
    fontWeight: '600',
  },
  transferNoteInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 12,
    fontSize: 13,
    marginHorizontal: 18,
    marginBottom: 18,
    textAlignVertical: 'top',
    backgroundColor: '#f8fafc',
    minHeight: 80,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 10,
    padding: 18,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonCancel: {
    backgroundColor: '#f1f5f9',
  },
  modalButtonCancelText: {
    color: '#475569',
    fontWeight: '600',
  },
  modalButtonTransfer: {
    backgroundColor: '#dc2626',
  },
  modalButtonConfirmText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  modalButtonDisabled: {
    backgroundColor: '#94a3b8',
  },
});