import { StyleSheet } from "react-native";

export default StyleSheet.create({
      container: { 
    flex: 1, 
    backgroundColor: '#f8fafc',
  },
  mainScrollView: { flex: 1 },
  contentContainer: { paddingBottom: 20 },
  
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  backButton: { padding: 4 },
  headerContent: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#0f172a' },
  exportButton: { padding: 6, backgroundColor: '#f0fdf4', borderRadius: 8 },
  subtitle: { 
    fontSize: 12, 
    color: '#64748b', 
    paddingHorizontal: 16, 
    paddingVertical: 8,
    backgroundColor: '#f8fafc',
  },
  
  summaryGrid: { 
    flexDirection: 'row', 
    gap: 8, 
    paddingHorizontal: 16, 
    paddingVertical: 12 
  },
  summaryCard: { 
    flex: 1, 
    borderRadius: 10, 
    padding: 12, 
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  summaryLabel: { fontSize: 9, color: '#64748b', fontWeight: '600', textAlign: 'center' },
  summaryValue: { fontSize: 14, fontWeight: '800', marginTop: 4 },
  
  filterSection: { 
    backgroundColor: '#ffffff', 
    borderRadius: 10, 
    padding: 12, 
    marginHorizontal: 16, 
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  searchRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  searchInputContainer: { 
    flex: 1, 
    flexDirection: 'row', 
    alignItems: 'center', 
    borderWidth: 0.5, 
    borderColor: '#e2e8f0', 
    borderRadius: 8, 
    paddingHorizontal: 10, 
    backgroundColor: '#f8fafc' 
  },
  searchInput: { 
    flex: 1, 
    paddingVertical: 8, 
    fontSize: 13, 
    color: '#1e293b',
    paddingHorizontal: 6,
  },
  filterToggle: { 
    padding: 8, 
    backgroundColor: '#f1f5f9', 
    borderRadius: 8, 
    position: 'relative' 
  },
  filterToggleActive: { backgroundColor: '#dc2626' },
  filterBadge: { 
    position: 'absolute', 
    top: -3, 
    right: -3, 
    backgroundColor: '#ef4444', 
    borderRadius: 99, 
    width: 16, 
    height: 16, 
    alignItems: 'center', 
    justifyContent: 'center' 
  },
  filterBadgeText: { color: '#ffffff', fontSize: 8, fontWeight: '700' },
  filtersGrid: { gap: 10, paddingTop: 10, borderTopWidth: 0.5, borderTopColor: '#f1f5f9' },
  dateRangeContainer: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  dateButton: { 
    flex: 1, 
    flexDirection: 'row', 
    alignItems: 'center', 
    borderWidth: 0.5, 
    borderColor: '#e2e8f0', 
    borderRadius: 8, 
    padding: 8, 
    gap: 4, 
    backgroundColor: '#f8fafc' 
  },
  dateButtonActive: { borderColor: '#dc2626', backgroundColor: '#fef2f2' },
  dateText: { fontSize: 11, color: '#64748b' },
  dateTextActive: { color: '#dc2626', fontWeight: '500' },
  dateSeparator: { color: '#94a3b8', fontSize: 12 },
  actionButtons: { flexDirection: 'row', gap: 8 },
  applyButton: { 
    flex: 1, 
    backgroundColor: '#dc2626', 
    borderRadius: 8, 
    padding: 10, 
    alignItems: 'center' 
  },
  applyButtonText: { fontWeight: '600', color: '#ffffff', fontSize: 12 },
  resetButton: { 
    flex: 1, 
    backgroundColor: '#f1f5f9', 
    borderRadius: 8, 
    padding: 10, 
    alignItems: 'center' 
  },
  resetButtonText: { color: '#64748b', fontSize: 12 },
  
  resultsHeader: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    paddingHorizontal: 16, 
    paddingVertical: 8,
    backgroundColor: '#f8fafc',
  },
  resultsCount: { fontSize: 12, fontWeight: '600', color: '#475569' },
  resultsHint: { fontSize: 11, color: '#94a3b8' },
  
  tableContainer: { 
    marginHorizontal: 16, 
    backgroundColor: '#ffffff', 
    borderRadius: 10, 
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  
  row: { 
    borderBottomWidth: 0.5, 
    borderBottomColor: '#f1f5f9',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  rowEven: { backgroundColor: '#ffffff' },
  rowOdd: { backgroundColor: '#fafafa' },
  rowContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  rowLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 10 },
  rowIndex: { fontSize: 12, color: '#94a3b8', fontWeight: '500', width: 24 },
  rowMainInfo: { flex: 1 },
  rowJobNo: { fontSize: 13, fontWeight: '700', color: '#2563eb' },
  rowCustomer: { fontSize: 12, color: '#0f172a', fontWeight: '500' },
  rowContact: { fontSize: 11, color: '#64748b' },
  rowRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  rowStats: { alignItems: 'flex-end' },
  rebillBadge: { 
    backgroundColor: '#fef3c7', 
    paddingHorizontal: 8, 
    paddingVertical: 2, 
    borderRadius: 12,
    marginBottom: 2,
  },
  rebillBadgeText: { fontSize: 11, fontWeight: '700', color: '#92400e' },
  rowTotal: { fontSize: 13, fontWeight: '700', color: '#6366f1' },
  expandIcon: { transform: [{ rotate: '0deg' }] },
  expandIconRotated: { transform: [{ rotate: '90deg' }] },
  
  expandedContainer: { 
    padding: 16, 
    backgroundColor: '#f0f9ff',
    borderTopWidth: 0.5,
    borderTopColor: '#e2e8f0',
  },
  expandedTitle: { 
    fontSize: 14, 
    fontWeight: '700', 
    color: '#1e40af', 
    marginBottom: 12 
  },
  
  historyItem: { 
    backgroundColor: '#ffffff', 
    borderRadius: 8, 
    padding: 12,
    marginBottom: 8,
    borderWidth: 0.5,
    borderColor: '#bfdbfe',
  },
  currentHistoryItem: { 
    backgroundColor: '#f0fdf4', 
    borderColor: '#86efac',
  },
  historyHeader: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    marginBottom: 6 
  },
  historyTitleContainer: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  historyNumber: { fontSize: 13, fontWeight: '700', color: '#1d4ed8' },
  currentLabel: { color: '#065f46' },
  historyDate: { fontSize: 11, color: '#94a3b8' },
  historyDetails: { gap: 3 },
  historyRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 1 },
  historyLabel: { fontSize: 12, color: '#475569' },
  historyValue: { fontSize: 12, fontWeight: '500', color: '#0f172a' },
  historyTotalRow: { marginTop: 2, paddingTop: 4, borderTopWidth: 0.5, borderTopColor: '#e2e8f0' },
  historyTotalLabel: { fontSize: 13, fontWeight: '600', color: '#1e293b' },
  historyTotalValue: { fontSize: 13, fontWeight: '700', color: '#6366f1' },
  historyRemarks: { fontSize: 11, color: '#94a3b8', fontStyle: 'italic', marginTop: 4 },
  historyBy: { fontSize: 10, color: '#94a3b8', marginTop: 2 },
  
  statusChip: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 12, alignSelf: 'flex-start' },
  statusChipText: { fontSize: 10, fontWeight: '600' },
  
  openButton: { 
    backgroundColor: '#2563eb', 
    borderRadius: 8, 
    padding: 10,
    alignItems: 'center',
    marginTop: 4,
  },
  openButtonText: { color: '#ffffff', fontSize: 13, fontWeight: '600' },
  
  emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40, gap: 8 },
  emptyText: { fontSize: 13, color: '#64748b' },
  loaderContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40, gap: 8 },
  loaderText: { color: '#64748b', fontSize: 13 }, 

});