
import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get('window');

export default StyleSheet.create({ 
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  backButton: {
    padding: 4,
    width: 40,
    alignItems: 'flex-start',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1e293b',
  },
  filterButton: {
    padding: 4,
    width: 40,
    alignItems: 'flex-end',
    position: 'relative',
  },
  filterBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#dc2626',
    borderRadius: 8,
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#ffffff',
  },
  filterBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#ffffff',
  },
  daysSelectorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    gap: 8,
  },
  daysSelectorLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
  },
  daysOptions: {
    flexDirection: 'row',
    gap: 6,
    flex: 1,
  },
  dayOption: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    minWidth: 36,
    alignItems: 'center',
  },
  dayOptionActive: {
    backgroundColor: '#dc2626',
  },
  dayOptionText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#475569',
  },
  dayOptionTextActive: {
    color: '#ffffff',
  },
  summaryContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
    minWidth: 70,
  },
  summaryCardCritical: {
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fca5a5',
  },
  summaryCardWarning: {
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fcd34d',
  },
  summaryCardFilter: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    justifyContent: 'center',
  },
  summaryCardValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1e293b',
  },
  summaryCardValueCritical: {
    fontSize: 22,
    fontWeight: '700',
    color: '#dc2626',
  },
  summaryCardValueWarning: {
    fontSize: 22,
    fontWeight: '700',
    color: '#d97706',
  },
  summaryCardLabel: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 2,
  },
  summaryCardLabelCritical: {
    fontSize: 10,
    color: '#dc2626',
    marginTop: 2,
    fontWeight: '600',
  },
  summaryCardLabelWarning: {
    fontSize: 10,
    color: '#d97706',
    marginTop: 2,
    fontWeight: '600',
  },
  jobsList: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    color: '#64748b',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
    paddingHorizontal: 20,
    gap: 12,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#64748b',
  },
  emptySubText: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
  },
  resetFilterButton: {
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#dc2626',
    borderRadius: 8,
  },
  resetFilterText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  jobCard: {
    backgroundColor: '#ffffff',
    borderLeftWidth: 4,
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  jobContent: {
    padding: 16,
  },
  jobHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  jobTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  jobNo: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2563eb',
  },
  urgencyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  urgencyText: {
    fontSize: 10,
    fontWeight: '600',
  },
  daysBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
  },
  daysText: {
    fontSize: 11,
    fontWeight: '600',
  },
  customerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  customerName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1e293b',
    flex: 1,
  },
  deviceInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  deviceTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  deviceText: {
    fontSize: 13,
    color: '#64748b',
    flex: 1,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '600',
  },
  assignedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
    marginBottom: 8,
  },
  assignedTo: {
    fontSize: 12,
    color: '#475569',
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
  },
  progressBar: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    borderRadius: 6,
    height: 6,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 6,
  },
  progressText: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '600',
    minWidth: 40,
    textAlign: 'right',
  },
  actionButtons: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 6,
  },
  viewButton: {
    backgroundColor: '#f8fafc',
  },
  viewButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3b82f6',
  },
  transferButton: {
    backgroundColor: '#f8fafc',
  },
  transferButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#f59e0b',
  },
  bottomSpacer: {
    height: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    width: width * 0.92,
    maxHeight: '85%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1e293b',
  },
  modalBody: {
    maxHeight: 500,
  },
  // Transfer Modal Styles - Fixed Alignment
  transferJobInfoCard: {
    backgroundColor: '#f8fafc',
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  transferInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
  },
  transferJobLabel: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '500',
    minWidth: 80,
  },
  transferJobValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1e293b',
    flex: 1,
    textAlign: 'right',
    marginLeft: 12,
  },
  transferJobStatus: {
    color: '#dc2626',
    textTransform: 'capitalize',
  },
  transferLabel: {
    fontSize: 14,
    color: '#475569',
    fontWeight: '600',
    marginBottom: 8,
    paddingHorizontal: 16,
  },
  transferSelect: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    marginHorizontal: 16,
    maxHeight: 220,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  transferOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  transferOptionActive: {
    backgroundColor: '#fef2f2',
  },
  transferOptionText: {
    fontSize: 14,
    color: '#1e293b',
    flex: 1,
    marginLeft: 10,
  },
  transferOptionSelected: {
    color: '#dc2626',
    fontWeight: '600',
  },
  transferCheckmark: {
    marginLeft: 'auto',
  },
  transferDivider: {
    height: 1,
    backgroundColor: '#e2e8f0',
    marginHorizontal: 0,
  },
  transferSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  transferSectionHeaderText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
  },
  transferEmpty: {
    padding: 16,
    alignItems: 'center',
  },
  transferEmptyText: {
    fontSize: 13,
    color: '#94a3b8',
  },
  transferNoteInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 14,
    fontSize: 14,
    marginHorizontal: 16,
    marginBottom: 12,
    textAlignVertical: 'top',
    backgroundColor: '#f8fafc',
    minHeight: 80,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonCancel: {
    backgroundColor: '#f1f5f9',
  },
  modalButtonCancelText: {
    color: '#475569',
    fontWeight: '600',
    fontSize: 15,
  },
  modalButtonTransfer: {
    backgroundColor: '#dc2626',
  },
  modalButtonConfirmText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 15,
  },
  modalButtonDisabled: {
    backgroundColor: '#94a3b8',
  },

});