import { Dimensions, StyleSheet } from "react-native";
import { COLORS, SPACING, FONTS, SHADOWS, BORDERS } from '../utils/theme';

const { width } = Dimensions.get('window');

export default StyleSheet.create({ 
      overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    width: width * 0.92,
    maxHeight: '85%',
    ...SHADOWS.large,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    ...FONTS.bold,
    fontSize: 16,
    color: COLORS.white,
  },
  body: {
    padding: SPACING.lg,
  },
  inputRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  inputGroupSmall: {
    flex: 1,
  },
  inputGroupDate: {
    flex: 1,
  },
  inputLabel: {
    ...FONTS.medium,
    fontSize: 12,
    color: COLORS.gray600,
    marginBottom: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: BORDERS.radius.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    ...FONTS.regular,
    fontSize: 14,
    color: COLORS.gray900,
    backgroundColor: COLORS.white,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  dateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: BORDERS.radius.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    gap: 8,
  },
  dateText: {
    ...FONTS.regular,
    fontSize: 14,
    color: COLORS.gray700,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    borderRadius: BORDERS.radius.md,
    gap: 4,
    alignSelf: 'flex-end',
    marginBottom: 2,
  },
  addButtonText: {
    ...FONTS.semibold,
    fontSize: 13,
    color: COLORS.white,
  },
  tableWrapper: {
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: BORDERS.radius.md,
    overflow: 'hidden',
    marginBottom: SPACING.md,
    maxHeight: 200,
  },
  tableContainer: {
    maxHeight: 160,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: COLORS.gray50,
    paddingVertical: 8,
    paddingHorizontal: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray200,
  },
  tableHeaderText: {
    ...FONTS.semibold,
    fontSize: 11,
    color: COLORS.gray600,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
  },
  tableCell: {
    ...FONTS.regular,
    fontSize: 12,
    color: COLORS.gray700,
  },
  colLabel: { flex: 2 },
  colAmount: { flex: 1.2 },
  colDate: { flex: 1.3 },
  colAction: { flex: 0.6, textAlign: 'center' },
  cellLabel: { ...FONTS.medium, color: COLORS.gray900 },
  cellAmount: { ...FONTS.semibold, color: COLORS.primary },
  cellDate: { fontSize: 11, color: COLORS.gray500 },
  deleteButton: {
    flex: 0.6,
    alignItems: 'center',
    padding: 4,
  },
  emptyState: {
    paddingVertical: SPACING.lg,
    alignItems: 'center',
  },
  emptyText: {
    ...FONTS.regular,
    fontSize: 13,
    color: COLORS.gray400,
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: SPACING.sm,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray200,
  },
  totalLabel: {
    ...FONTS.bold,
    fontSize: 15,
    color: COLORS.gray700,
  },
  totalValue: {
    ...FONTS.bold,
    fontSize: 16,
    color: '#16a34a',
  },
  footer: {
    flexDirection: 'row',
    gap: SPACING.sm,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.lg,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: BORDERS.radius.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.gray200,
    backgroundColor: COLORS.white,
  },
  cancelButtonText: {
    ...FONTS.semibold,
    fontSize: 14,
    color: COLORS.gray700,
  },
  saveButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: BORDERS.radius.md,
    alignItems: 'center',
    backgroundColor: '#16a34a',
  },
  saveButtonText: {
    ...FONTS.semibold,
    fontSize: 14,
    color: COLORS.white,
  },

});