import { Dimensions, StyleSheet } from "react-native";
import { COLORS, SPACING, FONTS, SHADOWS, BORDERS } from '../utils/theme';


const { width } = Dimensions.get('window');

export default StyleSheet.create({ 
     overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    width: width * 0.92,
    maxHeight: '88%',
    ...SHADOWS.large,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    ...FONTS.bold,
    fontSize: 16,
    color: COLORS.white,
  },
  body: {
    padding: SPACING.lg,
    flexGrow: 0,
    flexShrink: 1,
  },
  fieldWrapper: {
    marginBottom: SPACING.md,
  },
  inputLabel: {
    ...FONTS.medium,
    fontSize: 12,
    color: COLORS.gray600,
    marginBottom: 6,
  },
  categoryList: {
    gap: 8,
    paddingVertical: 4,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    backgroundColor: COLORS.white,
    marginRight: 8,
  },
  categoryChipSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  categoryChipText: {
    ...FONTS.medium,
    fontSize: 13,
    color: COLORS.gray700,
  },
  categoryChipTextSelected: {
    color: COLORS.white,
  },
  customInputWrapper: {
    marginTop: 8,
  },
  customInput: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: BORDERS.radius.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    ...FONTS.regular,
    fontSize: 14,
    color: COLORS.gray900,
    backgroundColor: '#F8FAFC',
  },
  row2: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: SPACING.md,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: BORDERS.radius.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    ...FONTS.regular,
    fontSize: 14,
    color: COLORS.gray900,
    backgroundColor: COLORS.white,
    width: '100%',
  },
  dateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: BORDERS.radius.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    gap: 8,
    width: '100%',
  },
  dateText: {
    ...FONTS.regular,
    fontSize: 14,
    color: COLORS.gray700,
    flex: 1,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primaryDark,
    paddingVertical: 13,
    borderRadius: BORDERS.radius.lg,
    gap: 8,
    marginTop: 2,
    marginBottom: SPACING.lg,
    width: '100%',
  },
  addButtonIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    ...FONTS.semibold,
    fontSize: 14,
    color: COLORS.white,
    letterSpacing: 0.2,
  },
  tableWrapper: {
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: BORDERS.radius.lg,
    backgroundColor: COLORS.white,
    overflow: 'hidden',
    marginBottom: SPACING.md,
    maxHeight: 180,
  },
  tableContainer: {
    maxHeight: 140,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    paddingVertical: 8,
    paddingHorizontal: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray200,
  },
  tableHeaderText: {
    ...FONTS.semibold,
    fontSize: 11,
    color: COLORS.gray600,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  tableCell: {
    ...FONTS.regular,
    fontSize: 12,
    color: COLORS.gray700,
  },
  colCategory: { flex: 1.5 },
  colAmount: { flex: 1 },
  colDate: { flex: 1.2 },
  colAction: { flex: 0.6, textAlign: 'center' },
  cellCategory: { ...FONTS.medium, color: COLORS.gray900 },
  cellAmount: { ...FONTS.semibold, color: COLORS.primary },
  cellDate: { fontSize: 11, color: COLORS.gray500 },
  deleteButton: {
    flex: 0.6,
    alignItems: 'center',
    padding: 4,
  },
  emptyState: {
    paddingVertical: SPACING.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.gray100,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.sm,
  },
  emptyText: {
    ...FONTS.medium,
    fontSize: 13,
    color: COLORS.gray500,
  },
  emptySubText: {
    ...FONTS.regular,
    fontSize: 11,
    color: COLORS.gray400,
    marginTop: 2,
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.sm,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray200,
  },
  totalLabel: {
    ...FONTS.bold,
    fontSize: 15,
    color: COLORS.gray700,
  },
  totalValue: {
    ...FONTS.bold,
    fontSize: 16,
    color: '#16a34a',
  },
  footer: {
    flexDirection: 'row',
    gap: SPACING.sm,
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.lg,
    backgroundColor: COLORS.white,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: BORDERS.radius.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.gray200,
    backgroundColor: COLORS.white,
  },
  cancelButtonText: {
    ...FONTS.semibold,
    fontSize: 14,
    color: COLORS.gray700,
  },
  saveButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: BORDERS.radius.md,
    alignItems: 'center',
    backgroundColor: '#16a34a',
  },
  saveButtonText: {
    ...FONTS.semibold,
    fontSize: 14,
    color: COLORS.white,
  },

});