
import { StyleSheet } from "react-native";
import { COLORS, SPACING, FONTS, SHADOWS,} from '../../utils/theme';

export default StyleSheet.create({ 

  container: {
    flex: 1,
    backgroundColor: '#f1f5f9',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    padding: SPACING.xl,
  },
  errorText: {
    ...FONTS.medium,
    fontSize: 16,
    color: COLORS.gray600,
    marginBottom: SPACING.lg,
  },
  errorButton: { minWidth: 120 },

  // ─── Header Card ────────────────────────────────────────────────────────
  headerCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    margin: SPACING.lg,
    padding: SPACING.lg,
    ...SHADOWS.medium,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  jobNumber: {
    ...FONTS.bold,
    fontSize: 20,
    color: '#0f172a',
    letterSpacing: 0.5,
  },
  jobDate: {
    ...FONTS.regular,
    fontSize: 12,
    color: COLORS.gray500,
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  statusText: {
    ...FONTS.semibold,
    fontSize: 12,
  },

  // ─── Banners ──────────────────────────────────────────────────────────────
  cancelledBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fee2e2',
    padding: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: 8,
    marginBottom: SPACING.sm,
    gap: 8,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  cancelledText: {
    ...FONTS.medium,
    fontSize: 12,
    color: '#991b1b',
    flex: 1,
  },
  invoicedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#dbeafe',
    padding: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: 8,
    marginBottom: SPACING.sm,
    gap: 8,
    borderWidth: 1,
    borderColor: '#bfdbfe',
  },
  invoicedText: {
    ...FONTS.medium,
    fontSize: 12,
    color: '#1d4ed8',
    flex: 1,
  },

  // ─── Summary Row ────────────────────────────────────────────────────────
  summaryRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: SPACING.sm,
  },
  summaryCard: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    padding: 10,
    borderLeftWidth: 3,
    gap: 8,
  },
  summaryCardIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryCardContent: {
    flex: 1,
  },
  summaryCardLabel: {
    ...FONTS.regular,
    fontSize: 10,
    color: COLORS.gray500,
  },
  summaryCardValue: {
    ...FONTS.bold,
    fontSize: 14,
    color: COLORS.gray900,
  },

  // ─── Status Section ──────────────────────────────────────────────────────
  statusSection: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
    padding: SPACING.lg,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  statusSectionTitle: {
    ...FONTS.semibold,
    fontSize: 14,
    color: '#0f172a',
    marginBottom: SPACING.md,
  },
  statusButtonsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statusButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    minWidth: 80,
    alignItems: 'center',
  },
  statusButtonDisabled: {
    opacity: 0.5,
  },
  statusButtonText: {
    ...FONTS.medium,
    fontSize: 11,
  },

  // ─── Detail Card ────────────────────────────────────────────────────────
  detailCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
    padding: SPACING.lg,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },

  // ─── Info Section ──────────────────────────────────────────────────────
  infoSection: {
    gap: 8,
  },
  infoSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  infoSectionTitle: {
    ...FONTS.bold,
    fontSize: 14,
    color: '#0f172a',
  },
  infoSectionContent: {
    gap: 2,
  },

  // ─── Detail Row ────────────────────────────────────────────────────────
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  detailRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  detailLabel: {
    ...FONTS.regular,
    fontSize: 12,
    color: COLORS.gray600,
  },
  detailValue: {
    ...FONTS.medium,
    fontSize: 12,
    color: '#0f172a',
    maxWidth: '55%',
    textAlign: 'right',
  },

  // ─── Visual Issues ─────────────────────────────────────────────────────
  visualIssuesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  visualIssueTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f3ff',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
    borderWidth: 1,
    borderColor: '#ede9fe',
  },
  visualIssueText: {
    ...FONTS.medium,
    fontSize: 11,
    color: '#7c3aed',
  },

  // ─── Table ─────────────────────────────────────────────────────────────
  tableContainer: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 4,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f8fafc',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  tableHeaderText: {
    ...FONTS.semibold,
    fontSize: 11,
    color: COLORS.gray600,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  tableCell: {
    ...FONTS.regular,
    fontSize: 11,
    color: '#0f172a',
  },
  tableColName: { flex: 2 },
  tableColQty: { flex: 0.8, textAlign: 'center' },
  tableColRate: { flex: 1, textAlign: 'right' },
  tableColAmount: { flex: 1.2, textAlign: 'right' },
  tableColLabel: { flex: 1.5 },
  tableColDate2: { flex: 1.5, textAlign: 'right' },
  cellName: { ...FONTS.medium },
  cellQty: { textAlign: 'center' },
  cellRate: { textAlign: 'right' },
  cellAmount: { ...FONTS.semibold, color: '#059669', textAlign: 'right' },
  cellDate: { textAlign: 'right', color: COLORS.gray500 },

  // ─── Rebill History ────────────────────────────────────────────────────
  rebillItem: {
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    padding: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  rebillHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  rebillNumber: {
    ...FONTS.semibold,
    fontSize: 12,
    color: '#1e40af',
  },
  rebillDate: {
    ...FONTS.regular,
    fontSize: 10,
    color: COLORS.gray500,
  },
  rebillDetails: {
    gap: 2,
  },
  rebillText: {
    ...FONTS.regular,
    fontSize: 11,
    color: '#0f172a',
  },
  rebillRemarks: {
    ...FONTS.italic,
    fontSize: 10,
    color: COLORS.gray500,
  },
  rebillBy: {
    ...FONTS.regular,
    fontSize: 9,
    color: COLORS.gray400,
  },

  // ─── Action Buttons Row 1 ──────────────────────────────────────────────
  actionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  actionButton: {
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 10,
    minWidth: 56,
  },
  actionLabel: {
    ...FONTS.medium,
    fontSize: 11,
    marginTop: 4,
    letterSpacing: 0.3,
  },

  // ─── Primary Action Buttons Row ────────────────────────────────────────
  primaryActionContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.xl,
    gap: 10,
  },

  // ─── Primary Button Styles ──────────────────────────────────────────────
  primaryBtn: {
    flex: 1,
    minWidth: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    ...SHADOWS.small,
  },
  primaryBtnText: {
    ...FONTS.semibold,
    fontSize: 14,
    color: COLORS.white,
    letterSpacing: 0.3,
  },
  primaryBtnTextDisabled: {
    ...FONTS.semibold,
    fontSize: 14,
    color: COLORS.gray500,
    letterSpacing: 0.3,
  },
  primaryBtnDisabled: {
    opacity: 0.6,
  },

  // ─── Button Variants ────────────────────────────────────────────────────
  primaryEditBtn: {
    flex: 1,
    minWidth: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    backgroundColor: '#3b82f6',
    ...SHADOWS.small,
    shadowColor: '#3b82f6',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryInvoiceBtn: {
    flex: 1,
    minWidth: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    backgroundColor: '#8b5cf6',
    ...SHADOWS.small,
    shadowColor: '#8b5cf6',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryInvoicedBtn: {
    flex: 1,
    minWidth: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    backgroundColor: '#e2e8f0',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  primaryRebillBtn: {
    flex: 1,
    minWidth: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    backgroundColor: '#f59e0b',
    ...SHADOWS.small,
    shadowColor: '#f59e0b',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryCancelBtn: {
    flex: 1,
    minWidth: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    backgroundColor: '#ef4444',
    ...SHADOWS.small,
    shadowColor: '#ef4444',
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#dc2626',
  },

  // ─── Modal ────────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: SPACING.lg,
    width: '90%',
    maxWidth: 400,
    ...SHADOWS.large,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.xs,
  },
  modalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modalTitle: {
    ...FONTS.bold,
    fontSize: 18,
    color: '#0f172a',
  },
  modalJobNo: {
    ...FONTS.semibold,
    fontSize: 14,
    color: '#3b82f6',
    marginBottom: SPACING.md,
  },
  modalWarningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef2f2',
    padding: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: 8,
    marginBottom: SPACING.md,
    gap: 8,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  modalWarningText: {
    ...FONTS.regular,
    fontSize: 13,
    color: '#991b1b',
    flex: 1,
  },
  modalLabel: {
    ...FONTS.medium,
    fontSize: 14,
    color: '#334155',
    marginBottom: SPACING.xs,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: SPACING.md,
    ...FONTS.regular,
    fontSize: 14,
    color: '#0f172a',
    minHeight: 100,
    textAlignVertical: 'top',
    backgroundColor: '#f8fafc',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  modalBtn: {
    flex: 1,
    paddingVertical: SPACING.md,
    borderRadius: 10,
    alignItems: 'center',
  },
  modalBtnDisabled: {
    opacity: 0.5,
  },
  modalCancelBtn: {
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  modalCancelText: {
    ...FONTS.semibold,
    fontSize: 14,
    color: '#64748b',
  },
  modalConfirmBtn: {
    backgroundColor: '#ef4444',
  },
  modalConfirmText: {
    ...FONTS.semibold,
    fontSize: 14,
    color: COLORS.white,
  },

  });