import { StyleSheet } from "react-native";
import { COLORS, SPACING, FONTS, SHADOWS,} from '../../utils/theme';

export default StyleSheet.create({ 
    container: {
        flex: 1,
        backgroundColor: '#F1F5F9',
      },
      contentContainer: {
        paddingBottom: 40,
      },
      formContainer: {
        padding: SPACING.md,
      },
      section: {
        backgroundColor: COLORS.white,
        borderRadius: 12,
        padding: SPACING.md,
        marginBottom: SPACING.md,
        ...SHADOWS.small,
        borderWidth: 1,
        borderColor: '#E2E8F0',
      },
      sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: SPACING.md,
        paddingBottom: SPACING.sm,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
      },
      sectionTitle: {
        ...FONTS.semibold,
        fontSize: 15,
        color: COLORS.gray900,
      },
      fieldWrapper: {
        marginBottom: SPACING.sm,
        width: '100%',
      },
      inputLabel: {
        ...FONTS.medium,
        fontSize: 12,
        color: COLORS.gray700,
        marginBottom: 4,
      },
      inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.gray200,
        borderRadius: 8,
        paddingHorizontal: SPACING.md,
        backgroundColor: COLORS.white,
        minHeight: 44,
        width: '100%',
      },
      inputField: {
        flex: 1,
        ...FONTS.regular,
        fontSize: 14,
        color: COLORS.gray900,
        paddingVertical: SPACING.xs,
        paddingRight: 4,
      },
      errorText: {
        ...FONTS.regular,
        fontSize: 11,
        color: COLORS.error,
        marginTop: 2,
      },
      row2: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 0,
      },
      row3: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 0,
      },
      checkboxGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginHorizontal: -4,
      },
      checkboxItem: {
        width: '50%',
        paddingHorizontal: 4,
        marginBottom: 2,
      },
      selectTrigger: {
        borderWidth: 1,
        borderColor: COLORS.gray200,
        borderRadius: 8,
        paddingHorizontal: SPACING.md,
        paddingVertical: 10,
        backgroundColor: COLORS.white,
        minHeight: 44,
        justifyContent: 'center',
        width: '100%',
      },
      selectTriggerSelected: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      selectTriggerName: {
        ...FONTS.semibold,
        fontSize: 14,
        color: COLORS.gray900,
      },
      selectTriggerPlaceholder: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      selectTriggerPlaceholderText: {
        ...FONTS.regular,
        fontSize: 14,
        color: COLORS.gray400,
      },
      workloadBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingVertical: 1,
        paddingHorizontal: 8,
        borderRadius: 20,
        alignSelf: 'flex-start',
        marginTop: 2,
      },
      workloadBadgeText: {
        ...FONTS.medium,
        fontSize: 10,
      },
      dateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.gray200,
        borderRadius: 8,
        paddingHorizontal: SPACING.md,
        paddingVertical: 10,
        backgroundColor: COLORS.white,
        minHeight: 44,
        gap: 8,
        width: '100%',
      },
      dateText: {
        ...FONTS.regular,
        fontSize: 14,
        color: COLORS.gray700,
        flex: 1,
      },
      clickableInput: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: COLORS.gray200,
        borderRadius: 8,
        paddingHorizontal: SPACING.md,
        paddingVertical: 10,
        backgroundColor: COLORS.white,
        minHeight: 44,
        width: '100%',
      },
      clickableInputLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
      },
      clickableInputText: {
        ...FONTS.medium,
        fontSize: 14,
        color: COLORS.gray900,
      },
      engineerTrigger: {
        borderWidth: 1,
        borderColor: COLORS.gray200,
        borderRadius: 8,
        paddingHorizontal: SPACING.md,
        paddingVertical: 10,
        backgroundColor: COLORS.white,
        minHeight: 44,
        justifyContent: 'center',
        width: '100%',
      },
      engineerTriggerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      engineerTriggerName: {
        ...FONTS.semibold,
        fontSize: 14,
        color: COLORS.gray900,
      },
      engineerTriggerBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 2,
      },
      engineerTriggerBadgeText: {
        ...FONTS.medium,
        fontSize: 11,
        color: '#16a34a',
      },
      engineerTriggerPlaceholder: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      engineerTriggerPlaceholderText: {
        ...FONTS.regular,
        fontSize: 14,
        color: COLORS.gray400,
      },
      engineerModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
      },
      engineerModalContent: {
        backgroundColor: COLORS.white,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingBottom: 32,
        maxHeight: '70%',
      },
      engineerModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.md,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.gray100,
      },
      engineerModalTitle: {
        ...FONTS.bold,
        fontSize: 17,
        color: COLORS.gray900,
      },
      engineerModalList: {
        paddingHorizontal: SPACING.lg,
        paddingTop: SPACING.sm,
      },
      engineerModalItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.gray100,
      },
      engineerModalItemSelected: {
        backgroundColor: '#EEF2FF',
        marginHorizontal: -SPACING.lg,
        paddingHorizontal: SPACING.lg,
        borderRadius: 8,
      },
      engineerModalItemDisabled: {
        opacity: 0.5,
      },
      engineerModalItemLeft: {
        flex: 1,
        gap: 4,
      },
      engineerModalItemName: {
        ...FONTS.semibold,
        fontSize: 15,
        color: COLORS.gray900,
      },
      engineerModalItemNameSelected: {
        color: COLORS.primary,
      },
      engineerModalItemNameDisabled: {
        color: COLORS.gray400,
      },
      engineerModalItemStatus: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingVertical: 2,
        paddingHorizontal: 8,
        borderRadius: 20,
        alignSelf: 'flex-start',
      },
      engineerModalItemStatusText: {
        ...FONTS.medium,
        fontSize: 11,
      },
      jobSheetHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
      },
      jobSheetHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
      },
      jobSheetLabel: {
        ...FONTS.medium,
        fontSize: 14,
        color: COLORS.gray600,
      },
      jobSheetNo: {
        ...FONTS.bold,
        fontSize: 16,
        color: COLORS.primary,
      },
      dateTimeContainer: {
        flexDirection: 'row',
        gap: SPACING.md,
      },
      dateTimeItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
      },
      dateTimeText: {
        ...FONTS.regular,
        fontSize: 12,
        color: COLORS.gray500,
      },
      searchSection: {
        marginBottom: SPACING.md,
      },
      searchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: COLORS.gray200,
        ...SHADOWS.small,
        overflow: 'hidden',
      },
      searchInput: {
        flex: 1,
        ...FONTS.regular,
        fontSize: 14,
        color: COLORS.gray900,
        paddingVertical: 10,
        paddingHorizontal: 8,
      },
      searchButton: {
        backgroundColor: COLORS.primary,
        paddingVertical: 10,
        paddingHorizontal: 16,
        justifyContent: 'center',
        alignItems: 'center',
      },
      searchButtonText: {
        ...FONTS.semibold,
        fontSize: 13,
        color: COLORS.white,
      },
      visualRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
        marginBottom: SPACING.sm,
      },
      visualSelectWrapper: {
        flex: 1,
      },
      visualSelect: {
        marginBottom: 0,
      },
      customFaultInput: {
        borderWidth: 1,
        borderColor: COLORS.gray200,
        borderRadius: 8,
        padding: SPACING.sm,
        marginTop: SPACING.xs,
        ...FONTS.regular,
        fontSize: 14,
        backgroundColor: COLORS.white,
      },
      removeVisualButton: {
        padding: SPACING.sm,
        marginLeft: SPACING.xs,
      },
      addVisualButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: COLORS.primary,
        borderRadius: 8,
        paddingVertical: SPACING.sm,
        marginTop: SPACING.xs,
        backgroundColor: '#EEF2FF',
        gap: 6,
      },
      addVisualText: {
        ...FONTS.medium,
        fontSize: 14,
        color: COLORS.primary,
      },
      financialSummary: {
        backgroundColor: '#F8FAFC',
        borderRadius: 8,
        padding: SPACING.md,
        marginBottom: SPACING.md,
        borderWidth: 1,
        borderColor: '#E2E8F0',
      },
      financialRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: SPACING.xs,
      },
      financialTotal: {
        borderTopWidth: 1,
        borderTopColor: '#E2E8F0',
        paddingTop: SPACING.sm,
        marginTop: SPACING.xs,
      },
      financialItem: {
        flex: 1,
        alignItems: 'center',
      },
      financialLabel: {
        ...FONTS.medium,
        fontSize: 11,
        color: COLORS.gray500,
        marginBottom: 2,
      },
      financialValue: {
        ...FONTS.bold,
        fontSize: 15,
        color: COLORS.gray900,
      },
      financialValueTotal: {
        color: COLORS.primary,
      },
      financialValueMargin: {
        color: '#16a34a',
      },
      financialValuePending: {
        color: '#D97706',
      },
      calcButton: {
        marginBottom: SPACING.sm,
      },
      previewItemsContainer: {
        backgroundColor: '#F8FAFC',
        borderRadius: 8,
        padding: SPACING.sm,
        marginBottom: SPACING.sm,
        borderWidth: 1,
        borderColor: '#E2E8F0',
      },
      previewItemsTitle: {
        ...FONTS.medium,
        fontSize: 12,
        color: COLORS.gray600,
        marginBottom: 4,
      },
      previewItemsItem: {
        ...FONTS.regular,
        fontSize: 12,
        color: COLORS.gray700,
        paddingVertical: 2,
      },
      previewItemsMore: {
        ...FONTS.medium,
        fontSize: 11,
        color: COLORS.gray400,
        marginTop: 2,
      },
      actionContainer: {
        marginTop: SPACING.md,
        marginBottom: SPACING.lg,
      },
      saveButtonPrimary: {
        backgroundColor: COLORS.primary,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: SPACING.md,
        borderRadius: 8,
        marginBottom: SPACING.md,
        gap: 8,
        ...SHADOWS.medium,
        width: '100%',
      },
      saveButtonText: {
        ...FONTS.bold,
        fontSize: 16,
        color: COLORS.white,
      },
      secondaryActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: SPACING.xs,
        flexWrap: 'wrap',
      },
      secondaryButton: {
        flex: 1,
        minWidth: 55,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.white,
        paddingVertical: 8,
        paddingHorizontal: 4,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: COLORS.gray200,
        ...SHADOWS.small,
        gap: 2,
      },
      newJobBtn: {
        borderColor: COLORS.primary,
        backgroundColor: '#EEF2FF',
      },
      estimateBtn: {
        borderColor: '#FDE68A',
      },
      invoiceBtn: {
        borderColor: '#DBEAFE',
      },
      secondaryButtonText: {
        ...FONTS.medium,
        fontSize: 10,
        color: COLORS.gray700,
        textAlign: 'center',
      },
      idProofUploadBox: {
        borderWidth: 2,
        borderColor: COLORS.gray200,
        borderRadius: 8,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8FAFC',
        borderStyle: 'dashed',
        width: '100%',
      },
      idProofUploadBoxDisabled: {
        borderColor: COLORS.gray300,
        backgroundColor: '#F1F5F9',
      },
      idProofUploadBoxHasImage: {
        borderStyle: 'solid',
        borderColor: COLORS.primary,
      },
      idProofPlaceholder: {
        alignItems: 'center',
        gap: 4,
      },
      idProofUploadText: {
        ...FONTS.regular,
        fontSize: 12,
        color: COLORS.gray500,
        marginTop: 4,
      },
      idProofUploadTextDisabled: {
        color: COLORS.gray400,
      },
      idProofPreview: {
        width: '100%',
        height: '100%',
        borderRadius: 8,
        resizeMode: 'cover',
      },
      idProofRemoveButton: {
        marginTop: SPACING.xs,
        alignSelf: 'flex-end',
      },
      idProofRemoveText: {
        ...FONTS.medium,
        fontSize: 11,
        color: COLORS.danger,
      },
      suggestionsDropdown: {
        position: 'absolute',
        top: 72,
        left: 0,
        right: 0,
        zIndex: 9999,
        elevation: 10,
        backgroundColor: COLORS.white,
        borderWidth: 1,
        borderColor: COLORS.gray200,
        borderRadius: 8,
        maxHeight: 240,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
      },
      suggestionItem: {
        paddingVertical: 10,
        paddingHorizontal: 12,
      },
      suggestionName: {
        ...FONTS.semibold,
        fontSize: 14,
        color: COLORS.gray900,
      },
      suggestionContact: {
        ...FONTS.regular,
        fontSize: 12,
        color: COLORS.gray500,
        marginTop: 2,
      },
      suggestionAddress: {
        ...FONTS.regular,
        fontSize: 11,
        color: COLORS.gray400,
        marginTop: 2,
      },
      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalSheet: {
        backgroundColor: COLORS.white,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingBottom: 32,
        maxHeight: '75%',
        width: '100%',
      },
      modalSheetHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.md,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.gray100,
      },
      modalSheetTitle: {
        ...FONTS.bold,
        fontSize: 17,
        color: COLORS.gray900,
      },
      modalSheetList: {
        paddingHorizontal: SPACING.lg,
        paddingTop: SPACING.sm,
      },
      modalContent: {
        backgroundColor: COLORS.white,
        borderRadius: 12,
        width: '90%',
        maxHeight: '80%',
        padding: SPACING.lg,
        ...SHADOWS.large,
      },
      modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: SPACING.md,
        paddingBottom: SPACING.sm,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.gray200,
      },
      modalTitle: {
        ...FONTS.bold,
        fontSize: 18,
        color: COLORS.gray900,
      },
      modalBody: {
        maxHeight: 400,
      },
      noResults: {
        textAlign: 'center',
        ...FONTS.regular,
        fontSize: 14,
        color: COLORS.gray500,
        padding: SPACING.xl,
      },
      searchResultItem: {
        paddingVertical: SPACING.md,
        paddingHorizontal: SPACING.sm,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.gray100,
      },
      resultJobNo: {
        ...FONTS.bold,
        fontSize: 14,
        color: COLORS.gray900,
      },
      resultCustomer: {
        ...FONTS.regular,
        fontSize: 12,
        color: COLORS.gray600,
      },
      resultStatus: {
        ...FONTS.regular,
        fontSize: 12,
        color: COLORS.gray500,
      },
      previewOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.55)',
        justifyContent: 'flex-end',
      },
      previewCard: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingTop: 20,
        paddingHorizontal: 20,
        paddingBottom: 28,
        maxHeight: '90%',
      },
      previewHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 4,
      },
      previewTitle: {
        ...FONTS.bold,
        fontSize: 18,
        color: COLORS.gray900,
      },
      previewSubTitle: {
        ...FONTS.regular,
        fontSize: 13,
        color: COLORS.gray500,
        marginBottom: 16,
      },
      previewScroll: {
        maxHeight: 400,
      },
      previewSection: {
        backgroundColor: '#F8FAFC',
        borderRadius: 8,
        padding: 12,
        marginBottom: 10,
      },
      previewSectionTitle: {
        ...FONTS.semibold,
        fontSize: 13,
        color: COLORS.gray700,
        marginBottom: 8,
      },
      previewRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 3,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
      },
      previewLabel: {
        ...FONTS.medium,
        fontSize: 12,
        color: COLORS.gray500,
      },
      previewValue: {
        ...FONTS.regular,
        fontSize: 12,
        color: COLORS.gray900,
      },
      previewValueHighlight: {
        color: COLORS.primary,
        fontWeight: 'bold',
      },
      previewTotalRow: {
        borderTopWidth: 1,
        borderTopColor: '#E2E8F0',
        paddingTop: SPACING.xs,
        marginTop: SPACING.xs,
      },
      previewTotalLabel: {
        fontWeight: 'bold',
        color: COLORS.gray800,
      },
      previewPendingValue: {
        fontWeight: 'bold',
        color: '#D97706',
      },
      previewButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 18,
      },
      previewBtn: {
        flex: 1,
        paddingVertical: 13,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 6,
      },
      previewCancelBtn: {
        backgroundColor: '#F1F5F9',
        borderWidth: 1,
        borderColor: COLORS.gray200,
      },
      previewCancelText: {
        ...FONTS.semibold,
        fontSize: 15,
        color: COLORS.gray700,
      },
      previewConfirmBtn: {
        backgroundColor: COLORS.primary,
      },
      previewConfirmText: {
        ...FONTS.semibold,
        fontSize: 15,
        color: '#fff',
      },
      alertOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      alertCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 28,
        width: '82%',
        alignSelf: 'center',
        alignItems: 'center',
      },
      alertTitle: {
        ...FONTS.bold,
        fontSize: 17,
        color: COLORS.gray900,
        textAlign: 'center',
        marginTop: 12,
        marginBottom: 8,
      },
      alertMsg: {
        ...FONTS.regular,
        fontSize: 13,
        color: COLORS.gray600,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 22,
      },
      alertButtons: {
        flexDirection: 'row',
        gap: 12,
        width: '100%',
      },
      alertBtn: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 10,
        alignItems: 'center',
      },
      alertCancelBtn: {
        backgroundColor: '#F1F5F9',
        borderWidth: 1,
        borderColor: COLORS.gray200,
      },
      alertCancelText: {
        ...FONTS.semibold,
        fontSize: 15,
        color: COLORS.gray700,
      },
      alertConfirmBtn: {
        backgroundColor: COLORS.primary,
      },
      alertConfirmText: {
        ...FONTS.semibold,
        fontSize: 15,
        color: '#fff',
      },

});